use pallet_zkghost::*;
use frame_support::{assert_ok, traits::OnInitialize};
use sp_io::TestExternalities;

// Minimal mock runtime imports from the real runtime are heavy; we use pallet in isolation with a tiny mock
mod mock {
    use super::*;
    use frame_support::{parameter_types, traits::Everything};
    use frame_system as system;
    use sp_runtime::traits::{BlakeTwo256, IdentityLookup};

    type UncheckedExtrinsic = frame_system::mocking::MockUncheckedExtrinsic<Test>;
    type Block = frame_system::mocking::MockBlock<Test>;

    frame_support::construct_runtime!(
        pub enum Test where
            Block = Block,
            NodeBlock = Block,
            UncheckedExtrinsic = UncheckedExtrinsic,
        {
            System: frame_system::{Pallet, Call, Config, Storage, Event<T>},
            ZkGhost: pallet_zkghost::{Pallet, Call, Storage, Event<T>},
        }
    );

    parameter_types! { pub const BlockHashCount: u64 = 250; }

    impl system::Config for Test {
        type BaseCallFilter = Everything;
        type BlockWeights = ();
        type BlockLength = ();
        type DbWeight = ();
        type Origin = RuntimeOrigin;
        type Call = RuntimeCall;
        type Nonce = u64;
        type Block = Block;
        type Hash = sp_core::H256;
        type Hashing = BlakeTwo256;
        type AccountId = u64;
        type Lookup = IdentityLookup<Self::AccountId>;
        type Header = sp_runtime::generic::Header<u64, BlakeTwo256>;
        type RuntimeEvent = RuntimeEvent;
        type BlockHashCount = BlockHashCount;
        type Version = (); type PalletInfo = PalletInfo; type AccountData = (); type OnNewAccount=(); type OnKilledAccount=(); type SystemWeightInfo=(); type SS58Prefix = frame_support::traits::ConstU16<42>; type OnSetCode=(); type MaxConsumers=frame_support::traits::ConstU32<16>;
    }

    impl pallet_zkghost::Config for Test {
        type RuntimeEvent = RuntimeEvent;
        type MaxVkLength = frame_support::traits::ConstU32<65536>;
        type MaxProofLength = frame_support::traits::ConstU32<65536>;
        type MaxPublicInputsLength = frame_support::traits::ConstU32<4096>;
        type MaxProofsPerBlock = frame_support::traits::ConstU32<50>;
    }

    pub fn new_ext() -> sp_io::TestExternalities {
        let t = system::GenesisConfig::default().build_storage::<Test>().unwrap();
        let mut ext: TestExternalities = t.into();
        ext.execute_with(|| { System::set_block_number(1); });
        ext
    }
}

#[test]
#[ignore] // Requires files generated by tools/prover-cli
fn e2e_submit_proof_from_files() {
    use mock::*;
    let mut ext = new_ext();
    ext.execute_with(|| {
        let vk = std::fs::read("vk.bin").expect("vk.bin");
        let proof = std::fs::read("proof.bin").expect("proof.bin");
        let inputs = std::fs::read("inputs.bin").expect("inputs.bin");
        assert_ok!(ZkGhost::set_vk(RuntimeOrigin::root(), 1u32, vk));
        // When built with feature zk-verify + std, the shim will verify
        assert_ok!(ZkGhost::submit_proof(RuntimeOrigin::signed(42), 1u32, proof, inputs));
    });
}
