use sc_client_api::ExecutorProvider;
use sc_consensus_aura::sr25519::AuthorityId as AuraId;
use sc_executor::NativeElseWasmExecutor;
use sc_service::{Configuration, error::Error, PartialComponents, TaskManager, TFullBackend, TFullClient};
use sc_telemetry::{Telemetry, TelemetryWorker};
use sp_api::ConstructRuntimeApi;
use sp_consensus_aura::AuraApi;
use sp_runtime::traits::BlakeTwo256;

pub type Block = zkghost_runtime::Block;
pub type Hashing = BlakeTwo256;

// Runtime API type imported from the runtime
pub type RuntimeApi = zkghost_runtime::RuntimeApi;

// Native executor dispatch (generated by runtime)
pub struct ExecutorDispatch;
impl sc_executor::NativeExecutionDispatch for ExecutorDispatch {
    type ExtendHostFunctions = (); // no custom host funcs for now

    fn dispatch(method: &str, data: &[u8]) -> Option<Vec<u8>> {
        zkghost_runtime::api::dispatch(method, data)
    }

    fn native_version() -> sc_executor::NativeVersion {
        zkghost_runtime::native_version()
    }
}

pub type FullClient = TFullClient<Block, RuntimeApi, NativeElseWasmExecutor<ExecutorDispatch>>;
pub type FullBackend = TFullBackend<Block>;

pub struct NewFullBase { pub task_manager: TaskManager }

pub fn new_partial(
    _config: &Configuration,
) -> Result<
    PartialComponents<
        FullClient,
        FullBackend,
        (),
        sc_consensus::import_queue::BasicQueue<Block>,
        sc_transaction_pool::FullPool<Block, FullClient>,
        (Option<Telemetry>, Option<TelemetryWorker>),
    >,
    Error,
> {
    // Placeholder partial components; implementing full wiring in next iteration
    Err(Error::Other("new_partial not yet implemented".into()))
}

pub fn new_full(
    config: Configuration,
) -> Result<(TaskManager, sc_service::RpcHandlers), Error> {
    // Placeholder full service; will be completed with Aura/GRANDPA, networking and RPC
    let (_role, _force_authoring) = (config.role.clone(), config.force_authoring);
    // Keep types available so compilation succeeds
    let _executor = NativeElseWasmExecutor::<ExecutorDispatch>::new(config.wasm_method, None);
    // Signal unimplemented at runtime; compile should succeed
    Err(Error::Other("new_full service wiring pending".into()))
}
